### ISSUE TITLE
PHP errors on merchant site

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1145]
# Description
Der Bank Blog has sent us an error log of several errors they believe are being caused by our plugin. After parsing this file, it appears it is 7 errors that are repeated frequently. We should resolve any errors stemming from our plugin.

### Error 1: Not unique table/alias: 'wp_bb1_postmeta' 
The following query needs a unique alias applied to the LEFT JOIN
`SELECT   wp_bb1_posts.ID FROM wp_bb1_posts  INNER JOIN wp_bb1_postmeta ON ( wp_bb1_posts.ID = wp_bb1_postmeta.post_id )  INNER JOIN wp_bb1_postmeta AS mt1 ON ( wp_bb1_posts.ID = mt1.post_id )  INNER JOIN wp_bb1_postmeta AS mt2 ON ( wp_bb1_posts.ID = mt2.post_id ) LEFT JOIN wp_bb1_postmeta ON (wp_bb1_postmeta.meta_key = '_subheading' AND wp_bb1_posts.ID = wp_bb1_postmeta.post_id)  WHERE 1=1  AND ( 
  wp_bb1_postmeta.meta_key = '_lp_access_to_all' 
  OR 
  ( mt1.meta_key = '_lp_access_to_except' AND mt1.meta_value NOT IN ('746','650','652','235','348') ) 
  OR 
  ( mt2.meta_key = '_lp_access_to_include' AND mt2.meta_value IN ('746','650','652','235','348') )
) AND wp_bb1_posts.post_type = 'lp_passes' AND ((wp_bb1_posts.post_status = 'publish' OR wp_bb1_posts.post_status = 'draft')) GROUP BY wp_bb1_posts.ID ORDER BY wp_bb1_posts.post_date DESC LIMIT 0, 100`

# Errors **NOT** Caused by LaterPay Plugin
_Documenting for our records._

### Error 2: Constant DISABLE_WP_CRON already defined
Constant DISABLE_WP_CRON already defined in /var/www/vhosts/der-bank-blog.de/httpdocs/wp-config.php on line 138

### Error 3: PHP Fatal error:  Uncaught Error: Call to a member function
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /var/www/vhosts/der-bank-blog.de/httpdocs/wp-includes/query.php:28
Stack trace:
#0 /var/www/vhosts/der-bank-blog.de/httpdocs/wp-content/plugins/mailster/classes/form.class.php(590): get_query_var('_mailster_form')
#1 /var/www/vhosts/der-bank-blog.de/httpdocs/wp-content/plugins/mailster/classes/form.class.php(534): MailsterForm->get_hidden_fields()
#2 /var/www/vhosts/der-bank-blog.de/httpdocs/wp-content/plugins/mailster/classes/frontpage.class.php(1102): MailsterForm->render(false)
#3 /var/www/vhosts/der-bank-blog.de/httpdocs/wp-includes/shortcodes.php(319): MailsterFrontpage->newsletter_signup_form(Array, '', 'newsletter_sign...')
#4 [internal function]: do_shortcode_tag(Array)
#5 /var/www/vhosts/der-bank-blog.de/httpdocs/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(newsle...', 'do_shortcode_ta...', '[newsletter_sig...')
#6 /var/www/vhosts/der-bank-blog.de/httpdocs/wp-content/plugins/adrotate-pro/adrotate-output.php(638): do_shor in /var/www/vhosts/der-bank-blog.de/httpdocs/wp-includes/query.php on line 28

### Error 4: PHP Warning:  Invalid argument supplied for foreach
PHP Warning:  Invalid argument supplied for foreach() in /var/www/vhosts/der-bank-blog.de/httpdocs/wp-content/plugins/nxs-snap-pro-upgrade/nxs-snap-pro-upgrade.php(41) : eval()'d code on line 60

### Error 5: PHP Warning:  strip_tags
PHP Warning:  strip_tags() expects parameter 1 to be string, array given in /var/www/vhosts/der-bank-blog.de/httpdocs/wp-content/plugins/social-networks-auto-poster-facebook-twitter-g/inc-cl/li.php on line 115

### Error 6: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted 
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vhosts/der-bank-blog.de/httpdocs/wp-includes/wp-db.php on line 1889

### Error 7: PHP Warning:  file_get_contents
PHP Warning:  file_get_contents(https://www.der-bank-blog.de/erfolgreiches-custody-banking/digital-banking/35535/): failed to open stream: HTTP request failed!  in /var/www/vhosts/der-bank-blog.de/httpdocs/wp-content/plugins/wp-worthy/wp-worthy.php on line 4955

**Comment by ksmoore125** [comment]
Full PHP error log [here](https://laterpay.slack.com/files/UDG7UK2VD/FGW4W17GA/php.log)

**Comment by ksmoore125** [comment]
We have not been able to reproduce this issue. The current query appears to be corrected ([see here](https://rtcamp.slack.com/archives/GA2P84GBZ/p1552655685001000?thread_ts=1552491229.002000&cid=GA2P84GBZ))

And this error does not appear on the merchant's sandbox account.
